[package]
name = "statistical_inference"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive = { git = "https://github.com/Banyc/primitive.git", tag = "v0.0.51" }
reikna = "0.12"
